### ISSUE TITLE
custom payload "unspecified"

### ISSUE THREAD

**Issue by isbkch** [eristemena/dialogflow-fulfillment-webhook-php#10]
I keep getting `unspecified` when I try to build a custom payload following documentation in: https://dialogflow.com/docs/reference/message-objects#custom_payload_message_object_2

![from DialogFlow diagnostic tool](https://i.imgur.com/C2rXniD.png)

Here is the response:
```    "webhookPayload": {
      "unspecified": {
        "payload": {
          "buttons": {
            "title": "Call Representative",
            "payload": "+15105551234",
            "type": "phone_number"
          },
          "template_type": "button",
          "text": "Give us a call?"
        },
        "type": "button",
        "platform": "facebook"
      }
    },
```

Here is how I'm building it:

``` 
$this->dialogAgent->reply(\Dialogflow\RichMessage\Payload::create([
    "type"     => "button",
    "platform" => "facebook",
    "payload"  => [
        "template_type" => "button",
        "text"          => "Give us a call?",
        "buttons" => [
            "type"    => "phone_number",
            "title"   => "Call Representative",
            "payload" => "+15105551234"
        ]
    ],
]));`

**Comment by eristemena** [comment]
Are you using Dialogflow console to get that response payload? That might cause the `unspecified`. 

You shouldn't worry about it, if the request is coming from Facebook (not Dialogflow console) the library will handle it automatically and put the correct platform based on the request source, in this case `facebook`.

You don't need to implicitly specify the `platform` in your payload, that's the idea of this library. You just need to concentrate on the platform's payload for your need.

See example how to send a custom Facebook's payload [here](https://github.com/eristemena/dialogflow-fulfillment-webhook-php/issues/6#issuecomment-416012078).

Hope it helps.

**Comment by isbkch** [comment]
Thank you for your answer, I've been trying to send this custom payload following the example you mentioned and FB documentation https://developers.facebook.com/docs/messenger-platform/reference/buttons/call/:

Following is my code
```
$this->dialogAgent->reply(\Dialogflow\RichMessage\Payload::create([
    'attachment' => [
        'type'    => 'template',
        'payload' => [
            "template_type" => "button",
            "text"          => "Give us a call?",
            "buttons" => [
                "type"    => "phone_number",
                "title"   => "Call Representative",
                "payload" => "+15105551234"
            ],
        ],
    ]
]));
```
But it never gets returned to the user, dialogflow just ignores it completely. Do you see anything wrong with it ?

**Comment by eristemena** [comment]
I think you missed one bracket there, `buttons` should contains array of buttons.

Try this,

```php
$this->dialogAgent->reply(\Dialogflow\RichMessage\Payload::create([
    'attachment' => [
        'type'    => 'template',
        'payload' => [
            "template_type" => "button",
            "text"          => "Give us a call?",
            "buttons" => [
                [
                    "type"    => "phone_number",
                    "title"   => "Call Representative",
                    "payload" => "+15105551234"
                ],
            ],
        ],
    ]
]));
```

**Comment by eristemena** [comment]
I don't think so. The way Dialogflow works as i understand it is a response of user's message. So you can only send one reply at a time.

Custom payload for Facebook is basically a `message` object of their [Send API](https://developers.facebook.com/docs/messenger-platform/reference/send-api), so you should consult to [Facebook doc](https://developers.facebook.com/docs/messenger-platform/reference/send-api#message) for possible message types you can send. As i understand it you can send text along with the attachment such as button or card. But you can only send one attachment per reply.

**Comment by isbkch** [comment]
I see. Thanks!
