### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by quasipickle** [eristemena/dialogflow-fulfillment-webhook-php#19]
Hi,

I've made an update to allow a fallback to plain text when the query source doesn't support a RichMessage.  I'm trying to run the tests, but calling `phpunit` from the cloned repository directory gives me the error:

`Cannot open file "/var/www/common/dialogflow-fulfillment-webhook-php/vendor/autoload.php".`

I see there is a `require-dev` section in composer.json, but I'm not too familiar with the ins-and-outs of composer or phpunit.  Is there an easy way to resolve this so I can write a new test and contribute a pull request?

**Comment by eristemena** [comment]
Have you tried run `vendor/bin/phpunit` under `/var/www/common/dialogflow-fulfillment-webhook-php`? like so,

```
$ cd /var/www/common/dialogflow-fulfillment-webhook-php
$ vendor/bin/phpunit
```

**Comment by quasipickle** [comment]
That did it.
