### ISSUE TITLE
Update packagist version

### ISSUE THREAD

**Issue by okaufmann** [eristemena/dialogflow-fulfillment-webhook-php#25]
Looks like packagist didn't receive the new version: 

- Github has v1.2.1: https://github.com/eristemena/dialogflow-fulfillment-webhook-php/releases/tag/1.2.1
- Packagist still has v1.2.0: https://packagist.org/packages/eristemena/dialogflow-fulfillment-webhook-php

Webhook broken?

**Comment by eristemena** [comment]
Ok i just update the packagist, please check again.
