### ISSUE TITLE
WebhookStatus: code: 3 message: "Webhook call failed.

### ISSUE THREAD

**Issue by dennisveenhof** [eristemena/dialogflow-fulfillment-webhook-php#45]
Received from google assistant the error message : WebhookStatus: code: 3 message: "Webhook call failed. Error: Failed to parse webhook JSON response: Expect message object but got: \"<br\"." ..

When posting the same JSON REQUEST by my self I don't have an error and receive a good response.

**Comment by dennisveenhof** [comment]
Working fine now!!!!

**Comment by repo-mc-company** [comment]
what was the issue please !!!
