### ISSUE TITLE
How to reset all context.

### ISSUE THREAD

**Issue by thecopt** [eristemena/dialogflow-fulfillment-webhook-php#8]
How to reset all context.

**Comment by eristemena** [comment]
Have you tried [`clearOutgoingContexts()`](https://github.com/eristemena/dialogflow-fulfillment-webhook-php/blob/master/docs/WebhookClient.md#webhookclientclearoutgoingcontexts)?

**Comment by thecopt** [comment]
Thank you @eristemena
